// Code generated by "stringer -trimprefix Job -type JobState"; DO NOT EDIT.

package ippsrv

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JobPending-3]
	_ = x[JobPendingHeld-4]
	_ = x[JobProcessing-5]
	_ = x[JobProcessingStopped-6]
	_ = x[JobCancelled-7]
	_ = x[JobAborted-8]
	_ = x[JobCompleted-9]
}

const _JobState_name = "PendingPendingHeldProcessingProcessingStoppedCancelledAbortedCompleted"

var _JobState_index = [...]uint8{0, 7, 18, 28, 45, 54, 61, 70}

func (i JobState) String() string {
	i -= 3
	if i < 0 || i >= JobState(len(_JobState_index)-1) {
		return "JobState(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _JobState_name[_JobState_index[i]:_JobState_index[i+1]]
}
