// Code generated by "stringer -trimprefix PS -type PrinterState"; DO NOT EDIT.

package ippsrv

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PSIdle-3]
	_ = x[PSProcessing-4]
	_ = x[PSStopped-5]
}

const _PrinterState_name = "IdleProcessingStopped"

var _PrinterState_index = [...]uint8{0, 4, 14, 21}

func (i PrinterState) String() string {
	idx := int(i) - 3
	if i < 3 || idx >= len(_PrinterState_index)-1 {
		return "PrinterState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrinterState_name[_PrinterState_index[idx]:_PrinterState_index[idx+1]]
}
