// Code generated by "stringer -type=printerState -trimprefix=state"; DO NOT EDIT.

package thermoprint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateIdle-0]
	_ = x[stateInitializing-1]
	_ = x[statePrinting-2]
	_ = x[statePaused-3]
	_ = x[stateWaitingRetry-4]
	_ = x[stateCompleted-5]
	_ = x[stateFailed-6]
}

const _printerState_name = "IdleInitializingPrintingPausedWaitingRetryCompletedFailed"

var _printerState_index = [...]uint8{0, 4, 16, 24, 30, 42, 51, 57}

func (i printerState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_printerState_index)-1 {
		return "printerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _printerState_name[_printerState_index[idx]:_printerState_index[idx+1]]
}
