// Code generated by "stringer -type=printerEvent -trimprefix=event"; DO NOT EDIT.

package thermoprint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eventStart-0]
	_ = x[eventNotificationHold-1]
	_ = x[eventNotificationRetransmit-2]
	_ = x[eventNotificationFinished-3]
	_ = x[eventInitComplete-4]
	_ = x[eventPacketsSent-5]
	_ = x[eventCancel-6]
	_ = x[eventError-7]
}

const _printerEvent_name = "StartNotificationHoldNotificationRetransmitNotificationFinishedInitCompletePacketsSentCancelError"

var _printerEvent_index = [...]uint8{0, 5, 21, 43, 63, 75, 86, 92, 97}

func (i printerEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_printerEvent_index)-1 {
		return "printerEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _printerEvent_name[_printerEvent_index[idx]:_printerEvent_index[idx+1]]
}
