// Code generated by "stringer -type StatusCode -linecomment"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SNoError-0]
	_ = x[SGenericError-1]
	_ = x[SHelpRequested-2]
	_ = x[SInvalidParameters-3]
	_ = x[SApplicationError-4]
}

const _StatusCode_name = "No ErrorGeneric ErrorHelp RequestedInvalid ParametersApplication Error"

var _StatusCode_index = [...]uint8{0, 8, 21, 35, 53, 70}

func (i StatusCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StatusCode_index)-1 {
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusCode_name[_StatusCode_index[idx]:_StatusCode_index[idx+1]]
}
