// Code generated by "stringer -type=printerEvent -trimprefix=event"; DO NOT EDIT.

package printers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eventStart-0]
	_ = x[eventNotificationHold-1]
	_ = x[eventNotificationRetransmit-2]
	_ = x[eventNotificationFinished-3]
	_ = x[eventInitComplete-4]
	_ = x[eventCancel-5]
	_ = x[eventError-6]
}

const _printerEvent_name = "StartNotificationHoldNotificationRetransmitNotificationFinishedInitCompleteCancelError"

var _printerEvent_index = [...]uint8{0, 5, 21, 43, 63, 75, 81, 86}

func (i printerEvent) String() string {
	if i < 0 || i >= printerEvent(len(_printerEvent_index)-1) {
		return "printerEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _printerEvent_name[_printerEvent_index[i]:_printerEvent_index[i+1]]
}
